### ISSUE TITLE
Repeatedly open and close same module will cause whole application crash

### ISSUE THREAD

**Issue by yaunm** [edwardkcyu/ituni-issues#12]
Issue can be reproduced by "Meeting Room Booking" and "CSAF Good Practice" modules.

**Comment by edwardkcyu** [comment]
the log
[app_crash_log.txt](https://github.com/edwardkcyu/ituni-issues/files/1204398/app_crash_log.txt)

**Comment by edwardkcyu** [comment]
due to double close splashscreen, fixed in next release
