### ISSUE TITLE
IT Staff App vs ITUNI

### ISSUE THREAD

**Issue by kychoi13** [edwardkcyu/ituni-issues#13]
1. In activation email, the link and the QR code goes to to IT staff app instead of ITUNI.
2. In the http://haitea.ha.org.hk, the download link goes to to IT staff app instead of ITUNI.
3. "ITUNI" is broader than the original "IT Staff App"(sharing of InfoQ info). Should http://haitea.ha.org.hk/index.html introduce more features of IT U and I e.g. product profile, CSAF practices etc. 
4. Will change the name "HA IT Staff App" to "ITUNI" and give some explanation of "ITUNI"?
5. Comment on the content of http://haitea.ha.org.hk/index.html
a. If "Bookmark" of ITUNI supports bookmarking the apps only, the description of "Bookmark" should be revised. It is saying it can bookmark the news, but it is not support in ITUNI now.
b. Suggest to simplify this sentence: "IT Staff App allow you to bookmark your favorite InfoQ article. It lets you have quick access to your favorite articles." --> "IT Staff App allow you to bookmark your favorite InfoQ article for quick access"
c. Typo: "IT Staff App provides social sharing feature for each articles. " --> "IT Staff App provides social sharing feature for each article. "
d. "That's Where We Are" --> "Where are we?"
e. Add hyper link at "QR Code of Website" for mobile app to open the page by finger click.
f. "© Hospital Authority 2016 All right reserved" --> "© Hospital Authority 2017 All right reserved"
6. Comment on the content of http://haitea.ha.org.hk/install_guide.html
a. Tell user to login by CORP a/c user ID & password
b. Typo: "Setting" -> "Settings"
![settings](https://user-images.githubusercontent.com/30786114/29052066-f71b8110-7c19-11e7-8b56-44651499bf37.png)

**Comment by edwardkcyu** [comment]
These comments are for IT Staff App v1 page, will provide a brand new page for ITUNI.
