### ISSUE TITLE
New version crashed with old version of IT staff app

### ISSUE THREAD

**Issue by kychoi13** [edwardkcyu/ituni-issues#14]
1. I have an old IT staff app, so when install this new version, this error is shown.
![capture _2017-08-07-17-54-14 1](https://user-images.githubusercontent.com/30786114/29021851-7db56ae6-7b99-11e7-80ad-b5db65e4252e.png)
2. After un-install the old app, I can install the new version. But when open the new version, this error is shown. 
![capture _2017-08-07-18-02-10 1](https://user-images.githubusercontent.com/30786114/29022155-bdbf6492-7b9a-11e7-9bb6-876188583a92.png)
3. I choose "RETRY", same error as step 2. 
4. I choose "LOAD OFFLINE DATA", this error is shown.
![capture _2017-08-07-18-05-15 1](https://user-images.githubusercontent.com/30786114/29022263-22f25e82-7b9b-11e7-96fe-dcc9f693bccc.png)

**Comment by edwardkcyu** [comment]
Wont have this problem for the production build
