### ISSUE TITLE
At OTP input screen, if the keyboard is closed, cannot open it again to revise the OTP input

### ISSUE THREAD

**Issue by kychoi13** [edwardkcyu/ituni-issues#16]
1. Input something in OTP
2. Pull down the keyboard
3. Focus the OTP input text box again. Expect the keyboard to show up again to enable re-input.
Actual: need to press "<-" again to go to previous page and come back to this OTP page again.
![capture _2017-08-07-18-29-06 1](https://user-images.githubusercontent.com/30786114/29023106-d67ec1d6-7b9e-11e7-9a05-00a5e5a4cfc8.png)
![capture _2017-08-07-18-29-57 1](https://user-images.githubusercontent.com/30786114/29023115-e6108774-7b9e-11e7-9fbc-4deec3c7e97b.png)

**Comment by edwardkcyu** [comment]
the keyboard cannot be hidden in next release
