### ISSUE TITLE
When maximize the app again, the app reloads and "Home" screen is shown. Can show the previous page before minimize the app instead?

### ISSUE THREAD

**Issue by kychoi13** [edwardkcyu/ituni-issues#20]
![capture _2017-08-07-19-08-28](https://user-images.githubusercontent.com/30786114/29052299-c865ee4e-7c1b-11e7-944e-08f86e5e4fea.png)
![capture _2017-08-08-09-26-08](https://user-images.githubusercontent.com/30786114/29052304-cfe6cf58-7c1b-11e7-945d-73c3f8968314.png)

**Comment by edwardkcyu** [comment]
You keep pressing the back button ?

**Comment by edwardkcyu** [comment]
Keep pressing back button means quit app, this is the expected behavior
