### ISSUE TITLE
In "News", click "image" can open the content. Can click "image" again to close the content?

### ISSUE THREAD

**Issue by kychoi13** [edwardkcyu/ituni-issues#21]
1. Go to "News"
2. Click "image" to open the content
3. Can click "image" to close the content"?
![capture _2017-08-08-08-33-31](https://user-images.githubusercontent.com/30786114/29052375-403bf756-7c1c-11e7-800b-46a75e1947ce.png)
![capture _2017-08-08-08-33-38](https://user-images.githubusercontent.com/30786114/29052376-41a16a86-7c1c-11e7-934d-fa56512aa720.png)

**Comment by edwardkcyu** [comment]
This is too creative, should follow the normal behaviour better
