### ISSUE TITLE
Can add a loading mask in Home Page and News Page?

### ISSUE THREAD

**Issue by CindyMankam** [edwardkcyu/ituni-issues#23]
Can add a loading logo/mask in Home Page and News Page?
It shows a white screen sometimes if it is slow to load the pages.
Thanks!
![20706184_10155744392212427_419217801_o](https://user-images.githubusercontent.com/30792077/29052772-bfdbeb5e-7c1e-11e7-8971-179b3f49f38e.jpg)

**Comment by edwardkcyu** [comment]
fixed in next release
