### ISSUE TITLE
Error of login failed prompt if login failed many times

### ISSUE THREAD

**Issue by CindyMankam** [edwardkcyu/ituni-issues#28]
1. input wrong password many many times
2. Input correct password again 
Error of "Login failed" prompt, and no response after pressing "OK" button
Must need to quit apps to open the apps again

![20706146_10155744418542427_459836369_o](https://user-images.githubusercontent.com/30792077/29053178-1571274e-7c21-11e7-9ee2-b1dfd34b677c.jpg)

**Comment by edwardkcyu** [comment]
only found in slow network ?

**Comment by edwardkcyu** [comment]
1. i think your are accidentally input a correct password , and backend server has problem at that time
2. Ios will not allow to exit app programatically. The behavior will be changed in next release
