### ISSUE TITLE
CSAF Good Practice - When open URL, sometimes asked for open by which browser, sometimes use default automatically.

### ISSUE THREAD

**Issue by kychoi13** [edwardkcyu/ituni-issues#30]
Asked for browser: DE1.2, DE1.3, DE1.4, DE2.2.1, DE2.3, DE2.4, etc.
![capture _2017-08-08-10-16-43](https://user-images.githubusercontent.com/30786114/29053491-fc90c9f8-7c22-11e7-98f1-3696a4c77ee3.png)

**Comment by edwardkcyu** [comment]
cannot reproduce in samsung galaxy S7

**Comment by edwardkcyu** [comment]
This should be device specific configuration problem, not related to the app logic
