### ISSUE TITLE
CSAF Good Practice - Icons not aligned

### ISSUE THREAD

**Issue by kychoi13** [edwardkcyu/ituni-issues#33]
1. In ITUNI's CSAF Good Practice app link icon <> Good Practice's app icon
![capture _2017-08-08-10-39-10](https://user-images.githubusercontent.com/30786114/29054008-fa5f1970-7c25-11e7-8e3c-be621c7e4f10.png)

2. In the group view, can use the corresponding icon of detail view?
![capture _2017-08-08-10-24-47](https://user-images.githubusercontent.com/30786114/29053670-ead2553c-7c23-11e7-81ba-6d080655bca3.png)
![capture _2017-08-08-10-26-03](https://user-images.githubusercontent.com/30786114/29053684-03acca4c-7c24-11e7-809c-8c5d52166792.png)

**Comment by edwardkcyu** [comment]
data fixed in keystonejs
