### ISSUE TITLE
CSAF Good Practice - Group vs Detail view icon is not representative

### ISSUE THREAD

**Issue by kychoi13** [edwardkcyu/ituni-issues#34]
Can use +/- to indicate the expand/collapse functionality?
![capture _2017-08-08-10-26-03](https://user-images.githubusercontent.com/30786114/29053731-46de9ec6-7c24-11e7-82f6-c6f3178f5b7e.png)
![capture _2017-08-08-10-24-47](https://user-images.githubusercontent.com/30786114/29053732-47e68996-7c24-11e7-8169-232eeeaec106.png)

**Comment by edwardkcyu** [comment]
the icon does not mean expand/collapse, instead, it means list view/ category view
