### ISSUE TITLE
If user has installed Slack app, can open Slack directly?

### ISSUE THREAD

**Issue by kychoi13** [edwardkcyu/ituni-issues#35]
Suggestions:
1. In "Applications", add a shortcut to open Slack app.
2. In "News" -> "Learning Communities" -> reference link -> open Slack app.
![capture _2017-08-08-10-46-32](https://user-images.githubusercontent.com/30786114/29054194-27aafa2e-7c27-11e7-9fa2-f2946c847ef3.png)
![capture _2017-08-08-10-46-42](https://user-images.githubusercontent.com/30786114/29054193-27a2c728-7c27-11e7-9597-2ff3cedad527.png)

**Comment by edwardkcyu** [comment]
no plan to include this dependency in the current stage
