### ISSUE TITLE
Update App with slow network?

### ISSUE THREAD

**Issue by CindyMankam** [edwardkcyu/ituni-issues#42]
When i try to update an application with new version, it keeps showing the "Updating application ..." loading mask with more than 10mins. 
![20726891_10155744613552427_998774532_o](https://user-images.githubusercontent.com/30792077/29055231-e8ad2016-7c2d-11e7-8dbb-531f562d03d4.jpg)

**Comment by edwardkcyu** [comment]
Duplicate of #7
