### ISSUE TITLE
Settings - should Settings be the default tab?

### ISSUE THREAD

**Issue by kychoi13** [edwardkcyu/ituni-issues#44]
1. When click "Settings" from menu, the Settings page is loaded but the header is "Profile"
2. Suggest to put the profile details right under the user's name instead of having a tab, so that can save 1 step for user see the settings.

![capture _2017-08-08-11-58-59](https://user-images.githubusercontent.com/30786114/29055844-88a771ea-7c31-11e7-8670-1da7398652b0.png)

![capture _2017-08-08-09-38-42](https://user-images.githubusercontent.com/30786114/29055885-c2294b28-7c31-11e7-8b5e-be2de8e2347e.png)

**Comment by edwardkcyu** [comment]
fixed in next release
