### ISSUE TITLE
Authentication method shown in Settings is empty

### ISSUE THREAD

**Issue by kychoi13** [edwardkcyu/ituni-issues#45]
1. After input the OTP, I quit app to skip the Authentication Method.
![capture _2017-08-08-11-54-15](https://user-images.githubusercontent.com/30786114/29056016-bf4bb6ec-7c32-11e7-928b-adf3cc6b42ce.png)

2. Open the app again.
3. The app requested me to assign a passcode. I input a passcode.
4. Go to Settings to check the authentication method. It is empty.
![capture _2017-08-08-12-07-38](https://user-images.githubusercontent.com/30786114/29056019-c109dd92-7c32-11e7-896b-887e6d287a7b.png)

**Comment by edwardkcyu** [comment]
The flow is updated in next release, can try again

**Comment by edwardkcyu** [comment]
fixed in next release
