### ISSUE TITLE
When install the Applications, if choose "Not allowed" for mobile's permission, the application still can install

### ISSUE THREAD

**Issue by kychoi13** [edwardkcyu/ituni-issues#46]
1. Go to Applications.
2. Click any application e.g. Product Profile (in grey)
3. Install
![capture _2017-08-08-18-50-22](https://user-images.githubusercontent.com/30786114/29068770-c11628da-7c6a-11e7-9dae-0d720f693f7a.png)
4. Choose "Not allowed"
![capture _2017-08-08-18-50-33](https://user-images.githubusercontent.com/30786114/29068772-c11fdff6-7c6a-11e7-8d19-22d4a0db7f33.png)
5. Close the message "Failed to open this app". 
![capture _2017-08-08-18-50-40](https://user-images.githubusercontent.com/30786114/29068773-c123eb96-7c6a-11e7-8bdb-62695f8a3788.png)
6. In main screen, the Product Profile icon is still grey. But when click it, the product profile can be loaded.
![capture _2017-08-08-18-51-00](https://user-images.githubusercontent.com/30786114/29068771-c11b5c1a-7c6a-11e7-87ab-921b5e7ed8e5.png)

**Comment by edwardkcyu** [comment]
fixed in next release
