### ISSUE TITLE
Unexpected "Selector" on the top when pushing touch on the Apps 

### ISSUE THREAD

**Issue by CindyMankam** [edwardkcyu/ituni-issues#6]
Unexpected "Selector" on the top when pushing touch on the Apps when a selection menu on the bottom

![20684217_10155742057612427_1051836179_o](https://user-images.githubusercontent.com/30792077/29015661-84496c9e-7b81-11e7-84ea-b260d2b2d41b.jpg)

**Comment by edwardkcyu** [comment]
fixed in next release
