### ISSUE TITLE
Keyboard screen disappeared if dragging on the passcode page

### ISSUE THREAD

**Issue by CindyMankam** [edwardkcyu/ituni-issues#8]
The Keyboard screen may disappear if dragging on the passcode page
The keyboard screen would not appear again unless quit the application and open it again
Result:
![20706061_10155742061852427_139595235_o](https://user-images.githubusercontent.com/30792077/29015799-190b5cde-7b82-11e7-9abd-1bc55bae69df.jpg)

**Comment by edwardkcyu** [comment]
fixed in next release
