### ISSUE TITLE
The white and blank circles not correct in Setup Passcode Page

### ISSUE THREAD

**Issue by CindyMankam** [edwardkcyu/ituni-issues#9]
1. In the Setup Passcode Page
2. Enter a passcode with 5 letters
3. delete the passcode one by one using "Del" button
4. The white circle still at the 5th circle instead of expected's blank circle
![20706036_10155742067932427_1687058658_o](https://user-images.githubusercontent.com/30792077/29015973-e6589756-7b82-11e7-9b96-22f378091bc3.jpg)

**Comment by edwardkcyu** [comment]
fixed in next release
